spring:
  application:
    name: step1

  datasource:
    url: jdbc:postgresql://localhost:5432/Step1
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

openapi: 3.0.0  
info:
  title: "LMS API"
  description: "API documentation for the Learning Management System (LMS)."
  version: "1.0.0"

mail:
  host: smtp.gmail.com
  port: 587
  username: boot83144@gmail.com
  password: lpth cqpn epyg oeqc
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
